
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sistema.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int textoA = 17;
  public static final int ancho = 22;
  public static final int texto = 24;
  public static final int cuerpo = 9;
  public static final int tipoAlineacion = 15;
  public static final int numero = 28;
  public static final int salto = 16;
  public static final int espacio = 12;
  public static final int alto = 21;
  public static final int cabecera = 8;
  public static final int alineacion = 14;
  public static final int titulo = 10;
  public static final int imagen = 19;
  public static final int igual = 6;
  public static final int EOF = 0;
  public static final int id = 25;
  public static final int boton = 23;
  public static final int path = 20;
  public static final int textoEntreComillas = 27;
  public static final int textoEntreEtiquetas = 26;
  public static final int error = 1;
  public static final int barra = 5;
  public static final int compi = 7;
  public static final int menorQue = 4;
  public static final int aceptacion = 2;
  public static final int parrafo = 13;
  public static final int textoB = 18;
  public static final int fondo = 11;
  public static final int mayorQue = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "aceptacion",
  "mayorQue",
  "menorQue",
  "barra",
  "igual",
  "compi",
  "cabecera",
  "cuerpo",
  "titulo",
  "fondo",
  "espacio",
  "parrafo",
  "alineacion",
  "tipoAlineacion",
  "salto",
  "textoA",
  "textoB",
  "imagen",
  "path",
  "alto",
  "ancho",
  "boton",
  "texto",
  "id",
  "textoEntreEtiquetas",
  "textoEntreComillas",
  "numero"
  };
}

