
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sistema.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int puntoYComa = 42;
  public static final int textoEntreEtiquetas = 31;
  public static final int mayorQue = 3;
  public static final int llaveAbre = 51;
  public static final int ancho = 26;
  public static final int finHS = 40;
  public static final int fondo = 11;
  public static final int textoB = 18;
  public static final int imagen = 23;
  public static final int textoA = 17;
  public static final int parentesisCierra = 36;
  public static final int compi = 7;
  public static final int igual = 6;
  public static final int identificador = 47;
  public static final int multiplicacion = 45;
  public static final int parrafo = 13;
  public static final int llaveCierra = 52;
  public static final int alto = 25;
  public static final int repetir = 48;
  public static final int alineacion = 14;
  public static final int menorIgual = 54;
  public static final int menorQue = 4;
  public static final int columnaC = 22;
  public static final int numero = 33;
  public static final int parentesisAbre = 35;
  public static final int fila = 20;
  public static final int menos = 44;
  public static final int tabla = 19;
  public static final int columna = 21;
  public static final int controlElse = 50;
  public static final int inicioHS = 39;
  public static final int EOF = 0;
  public static final int noIgual = 56;
  public static final int mas = 43;
  public static final int mayorIgual = 55;
  public static final int error = 1;
  public static final int entero = 60;
  public static final int or = 58;
  public static final int barra = 5;
  public static final int punto = 37;
  public static final int cuerpo = 9;
  public static final int textoEntreComillas = 32;
  public static final int cabecera = 8;
  public static final int id = 29;
  public static final int tipoAlineacion = 15;
  public static final int titulo = 10;
  public static final int igualIgual = 53;
  public static final int path = 24;
  public static final int texto = 28;
  public static final int not = 59;
  public static final int and = 57;
  public static final int salto = 16;
  public static final int booleano = 34;
  public static final int dolar = 41;
  public static final int borde = 30;
  public static final int espacio = 12;
  public static final int aceptacion = 2;
  public static final int division = 46;
  public static final int boton = 27;
  public static final int decimal = 61;
  public static final int controlIf = 49;
  public static final int interrogacion = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "aceptacion",
  "mayorQue",
  "menorQue",
  "barra",
  "igual",
  "compi",
  "cabecera",
  "cuerpo",
  "titulo",
  "fondo",
  "espacio",
  "parrafo",
  "alineacion",
  "tipoAlineacion",
  "salto",
  "textoA",
  "textoB",
  "tabla",
  "fila",
  "columna",
  "columnaC",
  "imagen",
  "path",
  "alto",
  "ancho",
  "boton",
  "texto",
  "id",
  "borde",
  "textoEntreEtiquetas",
  "textoEntreComillas",
  "numero",
  "booleano",
  "parentesisAbre",
  "parentesisCierra",
  "punto",
  "interrogacion",
  "inicioHS",
  "finHS",
  "dolar",
  "puntoYComa",
  "mas",
  "menos",
  "multiplicacion",
  "division",
  "identificador",
  "repetir",
  "controlIf",
  "controlElse",
  "llaveAbre",
  "llaveCierra",
  "igualIgual",
  "menorIgual",
  "mayorIgual",
  "noIgual",
  "and",
  "or",
  "not",
  "entero",
  "decimal"
  };
}

